name: Test github action
# on: push
on:
  workflow_dispatch:
    

jobs:
  shell-test:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      
      - name: multiline script
        run: |
          npm -v
